### ISSUE TITLE
No such file './README.md' when installing

### ISSUE THREAD

**Issue by nsh87** [bnlucas/python-basehash#3]
Getting the same error on OS X and Ubuntu 14.

``` shell
(env.example.com)vagrant@vagrant-ubuntu-trusty-64:~$ pip install basehash
Downloading/unpacking basehash
  Downloading BaseHash-3.0.1.zip
  Running setup.py (path:/server/env.example.com/build/basehash/setup.py) egg_info for package basehash
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/server/env.example.com/build/basehash/setup.py", line 26, in <module>
        long_description=open('./README.md').read() + '\n\n' + open('./HISTORY.md').read(),
    IOError: [Errno 2] No such file or directory: './README.md'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/server/env.example.com/build/basehash/setup.py", line 26, in <module>

    long_description=open('./README.md').read() + '\n\n' + open('./HISTORY.md').read(),

IOError: [Errno 2] No such file or directory: './README.md'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /server/env.example.com/build/basehash
```

**Comment by bnlucas** [comment]
I noticed this while trying to install on QPython on my Android. This has been fixed with a push for v3.0.3 which removes all read files. It is up on PyPi so `pip install basehash==3.0.3` is now working.
