### ISSUE TITLE
Missing "LICENSE" file in latest PyPi release (3.0.5)

### ISSUE THREAD

**Issue by Zujio** [bnlucas/python-basehash#8]
Running on MacOS:

```
$ pip download basehash==3.0.5 -i https://pypi.org/simple --isolated --no-cache-dir
Collecting basehash==3.0.5
  Downloading https://files.pythonhosted.org/packages/17/f4/1efa590add3ff79a792dc8e447fbe4c4f70eb1c53888e279bda351c1ba0c/BaseHash-3.0.5.tar.gz
  Saved ./BaseHash-3.0.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/9s/9k5_ss2n0tndcf3vmd0frxdw0000gq/T/pip-download-ywff62fs/basehash/setup.py", line 10, in <module>
        with open("LICENSE", "r") as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'LICENSE'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/9s/9k5_ss2n0tndcf3vmd0frxdw0000gq/T/pip-download-ywff62fs/basehash/
```

I see that there's an entry in the `.gitignore` file for a `MANIFEST.in` but don't see one checked in to the repository. The fix is likely that the relevant missing non-code files need to be specified there before next publication.

**Comment by bnlucas** [comment]
This has been fixed.
